apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: django:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000