FROM python:3.9

RUN apt-get update \
    && apt-get install -y vim git

RUN pip install --upgrade pip wheel setuptools
ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
RUN pip install git+https://github.com/azure-samples/ms-identity-python-utilities@main

COPY code/. /root/code

WORKDIR /root/code/test

ENTRYPOINT [ "bash", "run_server.sh" ]
