FROM nginx:1.25.0-alpine3.17-slim

RUN rm /etc/nginx/conf.d/default.conf
RUN rm -r /etc/ssl/
RUN mkdir /etc/ssl/

ADD ./ssl/ /etc/ssl/
COPY ./default.conf /etc/nginx/conf.d
COPY ./ssl-redirect.conf /etc/nginx/default.d
